# Generated by Django 6.0.2 on 2026-02-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(blank=True, max_length=128)),
                ('call_id', models.CharField(blank=True, max_length=128)),
                ('record_file_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('audio_file_path', models.CharField(blank=True, max_length=512)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.CharField(max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.callwebhookevent')),
            ],
        ),
    ]
