# Generated by Django 6.0.2 on 2026-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callwebhookevent',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callwebhookevent',
            name='lead_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
