# Generated by Django 6.0.2 on 2026-02-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_callwebhookevent_dedupe_key_callwebhookevent_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCallArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_event_id', models.PositiveIntegerField(db_index=True)),
                ('call_id', models.CharField(blank=True, max_length=128)),
                ('lead_id', models.CharField(blank=True, max_length=128)),
                ('record_file_id', models.CharField(blank=True, max_length=128)),
                ('audio_file_path', models.CharField(blank=True, max_length=512)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='communicati_created_2ef264_idx'), models.Index(fields=['call_id'], name='communicati_call_id_2d72f0_idx'), models.Index(fields=['lead_id'], name='communicati_lead_id_5be101_idx')],
            },
        ),
    ]
