# Generated by Django 6.0.2 on 2026-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_processedcallarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='callwebhookevent',
            name='deal_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='processedcallarchive',
            name='deal_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='processedcallarchive',
            index=models.Index(fields=['deal_id'], name='communicati_deal_id_019cf0_idx'),
        ),
    ]
