# Generated by Django 6.0.2 on 2026-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_callwebhookevent_deal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callwebhookevent',
            name='contact_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='processedcallarchive',
            name='contact_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='processedcallarchive',
            index=models.Index(fields=['contact_id'], name='communicati_contact_6d500b_idx'),
        ),
    ]
