# Generated by Django 5.2.4 on 2026-03-30 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BitrixSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=128)),
                ("action", models.CharField(max_length=64)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=False)),
                ("error_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="call_queue__entity__00b4d5_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="call_queue__action_62381d_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="call_queue__success_1c79ed_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("deal", "Сделки"), ("lead", "Лиды")],
                        default="deal",
                        max_length=16,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активна"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("filters_json", models.JSONField(blank=True, default=dict)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CallQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("deal", "Сделки"), ("lead", "Лиды")],
                        default="deal",
                        max_length=16,
                    ),
                ),
                ("bitrix_entity_id", models.BigIntegerField()),
                ("bitrix_contact_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("lead_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "source_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("stage_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "stage_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "responsible_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "responsible_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("in_progress", "В работе"),
                            ("done", "Завершен"),
                            ("postponed", "Перезвонить позже"),
                            ("skipped", "Пропущен"),
                            ("failed", "Недозвон"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("attempts_count", models.PositiveIntegerField(default=0)),
                (
                    "last_call_result",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("last_call_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_provider_call_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("bitrix_url", models.URLField(blank=True, default="")),
                ("needs_manual_processing", models.BooleanField(default=False)),
                ("repeat_unanswered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_call_queue_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="call_queue.callsession",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CallAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "finished_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("no_answer", "Не ответил"),
                            ("busy", "Занято"),
                            ("unavailable", "Недоступен"),
                            ("success", "Успешно"),
                            ("postponed", "Перезвонить позже"),
                            ("skipped", "Пропустить"),
                        ],
                        max_length=32,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "provider_call_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="call_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "queue_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="call_queue.callqueueitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["queue_item", "created_at"],
                        name="call_queue__queue_i_309279_idx",
                    ),
                    models.Index(
                        fields=["manager", "created_at"],
                        name="call_queue__manager_f1cfdf_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="callqueueitem",
            index=models.Index(
                fields=["session", "status"], name="call_queue__session_5d66e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callqueueitem",
            index=models.Index(
                fields=["session", "assigned_to"], name="call_queue__session_a7256b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callqueueitem",
            index=models.Index(
                fields=["status", "locked_at"], name="call_queue__status_080fd7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="callqueueitem",
            constraint=models.UniqueConstraint(
                fields=("session", "entity_type", "bitrix_entity_id"),
                name="call_queue_unique_session_entity",
            ),
        ),
    ]
