# Generated by Django 5.2.4 on 2026-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bitrix_deal_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="ID сделки в Bitrix24"
                    ),
                ),
                (
                    "initial_bitrix_task_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID первой задачи в Bitrix24",
                    ),
                ),
                (
                    "bitrix_task_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID текущей задачи в Bitrix24",
                    ),
                ),
                (
                    "moderator_bitrix_user_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="ID модератора в Bitrix24"
                    ),
                ),
                (
                    "responsible_bitrix_user_id",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID ответственного за сделку",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Описание первой задачи"
                    ),
                ),
                (
                    "initial_task_created",
                    models.BooleanField(
                        default=False, verbose_name="Первая задача уже создана"
                    ),
                ),
                (
                    "attempts_total",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Всего создано задач"
                    ),
                ),
                (
                    "attempts_today",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Задач создано сегодня"
                    ),
                ),
                (
                    "attempts_last_reset_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего сброса attempts_today",
                    ),
                ),
                (
                    "entered_logic_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Когда сделка зарегистрирована в логике",
                    ),
                ),
                (
                    "current_stage_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Последняя известная стадия сделки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активна в мониторинге"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("active", "Активна"),
                            ("success", "Успешно завершена"),
                            ("stopped", "Остановлена"),
                            ("skipped", "Исключена"),
                            ("error", "Ошибка"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "status_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарий статуса"
                    ),
                ),
                (
                    "last_task_closed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Когда в последний раз закрыли задачу",
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Когда в последний раз проверяли",
                    ),
                ),
                (
                    "raw_deal_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Последние сырые данные сделки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Мониторинг лида из модерации",
                "verbose_name_plural": "Мониторинг лидов из модерации",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "status"],
                        name="lead_contro_is_acti_32f075_idx",
                    ),
                    models.Index(
                        fields=["responsible_bitrix_user_id"],
                        name="lead_contro_respons_bd2c9b_idx",
                    ),
                    models.Index(
                        fields=["current_stage_id"],
                        name="lead_contro_current_096a01_idx",
                    ),
                ],
            },
        ),
    ]
