# Generated by Django 5.2.4 on 2026-08-27 09:02

import django.db.models.deletion
import django.utils.timezone
import urlshorter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtmMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtmSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SlugField(help_text='Короткий код в адресе редиректа', max_length=150, unique=True)),
                ('link_type', models.CharField(choices=[('site', 'Сайт (классическая UTM)'), ('bot', 'Telegram-бот'), ('other', 'Прочие площадки')], max_length=10)),
                ('destination', models.URLField(help_text="Целевая ссылка (для типа 'бот' — адрес бота)")),
                ('utm_campaign', models.CharField(max_length=100, validators=[urlshorter.models.validate_utm_free_text])),
                ('utm_content', models.CharField(blank=True, max_length=100, validators=[urlshorter.models.validate_utm_free_text])),
                ('utm_term', models.CharField(blank=True, max_length=100, validators=[urlshorter.models.validate_utm_free_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_block', models.ForeignKey(blank=True, help_text='Только для link_type=bot', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='urlshorter.botblock')),
                ('utm_medium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='urlshorter.utmmedium')),
                ('utm_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='urlshorter.utmsource')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_bot_preview', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urlshorter.marketinglink')),
            ],
        ),
        migrations.AddConstraint(
            model_name='marketinglink',
            constraint=models.UniqueConstraint(fields=('link_type', 'destination', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'bot_block'), name='unique_marketing_link_combo'),
        ),
    ]
