# Generated by Django 5.2.4 on 2025-11-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentapplication',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalinstallmentpayment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
