# Generated by Django 5.2.4 on 2025-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='preferred_payment_day',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
