# Generated by Django 5.2.4 on 2025-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extra_court_costs',
            field=models.BooleanField(default=False, help_text='Оплачены доп. судебные расходы'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deposit',
            field=models.BooleanField(default=False, help_text='Оплачен судебный депозит'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='publication',
            field=models.BooleanField(default=False, help_text='Оплачена публикация'),
        ),
    ]
