# Generated by Django 5.2.4 on 2025-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_contract_extra_court_costs_alter_contract_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
