# Generated by Django 5.2.4 on 2025-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_contract_preferred_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='publication',
            field=models.BooleanField(default=False),
        ),
    ]
