# Generated by Django 5.2.4 on 2025-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_contract_deposit_contract_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
