# Generated by Django 5.2.4 on 2025-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_installmentpayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualpayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
