# Generated by Django 5.2.4 on 2025-09-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_installmentpayment_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments.actualpayment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='payments.installmentpayment')),
            ],
        ),
    ]
