# Generated by Django 5.2.4 on 2025-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_actualpayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualpayment',
            name='is_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
