# Generated by Django 5.2.4 on 2025-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_actualpayment_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='bank_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
