# Generated by Django 5.2.4 on 2026-02-16 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadreport', '0002_salesmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadentry',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_entries', to='leadreport.salesmanager'),
        ),
    ]
