# Generated by Django 5.2.4 on 2026-02-16 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadreport', '0004_salesmanager_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCredentialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_logs', to='leadreport.salesmanager')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
    ]
