# Generated by Django 5.2.4 on 2025-12-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название приза')),
                ('image', models.ImageField(upload_to='prizes/', verbose_name='Картинка приза')),
                ('chance', models.FloatField(help_text='Относительный вес. Например: 0.1, 1, 5', verbose_name='Шанс выпадения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Код билета')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='SpinResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(verbose_name='Выигрыш')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.prize', verbose_name='Приз')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spin_result', to='administration.ticket', verbose_name='Билет')),
            ],
            options={
                'verbose_name': 'Результат прокрута',
                'verbose_name_plural': 'Результаты прокрута',
            },
        ),
    ]
