# Generated by Django 5.2.4 on 2026-02-02 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainee', 'Trainee')], default='trainee', max_length=32)),
                ('bitrix_user_id', models.BigIntegerField(db_index=True)),
                ('bitrix_portal', models.CharField(db_index=True, max_length=255)),
                ('bitrix_active', models.BooleanField(default=True)),
                ('birthday', models.DateField(blank=True, help_text='Дата рождения из Bitrix24', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bitrix_portal', 'bitrix_user_id'), name='uniq_bitrix_user_per_portal')],
            },
        ),
    ]
