# Generated by Django 5.2.4 on 2026-02-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_platform', '0002_traineeprofile_delete_bitrixaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='in_progress', max_length=32)),
                ('attempt_number', models.IntegerField(default=1)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='education_platform.traineeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(db_index=True)),
                ('answer_type', models.CharField(choices=[('choice', 'Choice'), ('text', 'Text'), ('other', 'Other')], default='choice', max_length=16)),
                ('error_type', models.CharField(max_length=64)),
                ('user_answer', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='education_platform.testattempt')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='not_started', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=128)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='education_platform.traineeprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['trainee', 'status'], name='education_p_trainee_5fbdcc_idx'), models.Index(fields=['block_id', 'status'], name='education_p_block_i_30050e_idx')],
                'unique_together': {('trainee', 'block_id')},
            },
        ),
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='education_platform.traineeprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['trainee', 'created_at'], name='education_p_trainee_3c9bf3_idx'), models.Index(fields=['event_type', 'created_at'], name='education_p_event_t_25340c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['trainee', 'test_id'], name='education_p_trainee_ed961d_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test_id', 'status'], name='education_p_test_id_12ba72_idx'),
        ),
        migrations.AddIndex(
            model_name='answererror',
            index=models.Index(fields=['attempt', 'question_id'], name='education_p_attempt_b6ed9b_idx'),
        ),
        migrations.AddIndex(
            model_name='answererror',
            index=models.Index(fields=['question_id'], name='education_p_questio_bca5b8_idx'),
        ),
    ]
