# Generated by Codex on 2026-02-18

from django.db import migrations


DEPARTMENTS = {
    "sales": "Продажи",
    "marketing": "Маркетинг",
    "moderation": "Модерация",
    "firstline": "Первая линия",
    "support": "Отдел сопровождения",
    "law": "Юридический",
}

COURSES = [
    {
        "id": 1,
        "name": "Онбординг платформы",
        "description": "Базовые процессы, интерфейс и правила работы с клиентом.",
        "image_url": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
        "photo_url": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80",
        "departments": ["sales", "marketing", "moderation", "firstline", "support", "law"],
        "module_ids": [101, 102, 103],
    },
    {
        "id": 2,
        "name": "Продажи и конверсия",
        "description": "Скрипты, обработка возражений и контроль воронки.",
        "image_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
        "photo_url": "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80",
        "departments": ["sales", "firstline"],
        "module_ids": [201, 202],
    },
    {
        "id": 3,
        "name": "Сервис и сопровождение",
        "description": "Стандарты коммуникации, эскалации и SLA.",
        "image_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
        "photo_url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
        "departments": ["support", "moderation"],
        "module_ids": [301, 302],
    },
]

MODULES = {
    101: {
        "course_id": 1,
        "name": "Навигация по платформе",
        "description": "Основные разделы, роли и ежедневная рутина сотрудника.",
        "video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "order": 1,
    },
    102: {
        "course_id": 1,
        "name": "Регламенты и метрики",
        "description": "Цели обучения и базовые KPI по отделам.",
        "video_url": "https://www.youtube.com/embed/9bZkp7q19f0",
        "order": 2,
    },
    103: {
        "course_id": 1,
        "name": "Чек-лист первой недели",
        "description": "Что нужно настроить и проверить в первые 5 рабочих дней.",
        "video_url": "https://www.youtube.com/embed/3JZ_D3ELwOQ",
        "order": 3,
    },
    201: {
        "course_id": 2,
        "name": "Скрипт первого контакта",
        "description": "Формула открытия диалога и фиксации потребности.",
        "video_url": "https://www.youtube.com/embed/JGwWNGJdvx8",
        "order": 1,
    },
    202: {
        "course_id": 2,
        "name": "Возражения и дожим",
        "description": "Техники без давления, которые повышают конверсию.",
        "video_url": "https://www.youtube.com/embed/kJQP7kiw5Fk",
        "order": 2,
    },
    301: {
        "course_id": 3,
        "name": "Тон коммуникации",
        "description": "Шаблоны ответов и нормы деловой переписки.",
        "video_url": "https://www.youtube.com/embed/fRh_vgS2dFE",
        "order": 1,
    },
    302: {
        "course_id": 3,
        "name": "Эскалации и SLA",
        "description": "Когда и как эскалировать кейс без потери клиента.",
        "video_url": "https://www.youtube.com/embed/2Vv-BfVoq4g",
        "order": 2,
    },
}


def seed_catalog(apps, schema_editor):
    Department = apps.get_model("education_platform", "Department")
    Course = apps.get_model("education_platform", "Course")
    Module = apps.get_model("education_platform", "Module")
    ModuleTest = apps.get_model("education_platform", "ModuleTest")

    department_map = {}
    for code, name in DEPARTMENTS.items():
        dep, _ = Department.objects.get_or_create(code=code, defaults={"name": name, "is_active": True})
        if dep.name != name:
            dep.name = name
            dep.save(update_fields=["name"])
        department_map[code] = dep

    for course_data in COURSES:
        course, _ = Course.objects.get_or_create(
            id=course_data["id"],
            defaults={
                "name": course_data["name"],
                "description": course_data["description"],
                "image_url": course_data["image_url"],
                "photo_url": course_data["photo_url"],
                "is_active": True,
            },
        )
        course.departments.set([department_map[code] for code in course_data["departments"] if code in department_map])

    for module_id, module_data in MODULES.items():
        module, _ = Module.objects.get_or_create(
            id=module_id,
            defaults={
                "course_id": module_data["course_id"],
                "name": module_data["name"],
                "description": module_data["description"],
                "video_url": module_data["video_url"],
                "order": module_data["order"],
                "is_active": True,
            },
        )
        ModuleTest.objects.get_or_create(
            module=module,
            defaults={
                "name": "Проверка модуля",
                "description": "Нажмите «Отправить тест», чтобы завершить модуль.",
                "max_score": 0,
                "passing_score": 0,
                "max_attempts": 3,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("education_platform", "0004_department_course_module_moduletest_testquestion_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_catalog, migrations.RunPython.noop),
    ]
