# Generated by Django 5.2.4 on 2026-05-21 08:45

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_platform", "0005_seed_lms_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="private_video",
            field=models.FileField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=settings.PRIVATE_MEDIA_ROOT
                ),
                upload_to="education/videos/",
            ),
        ),
        migrations.CreateModel(
            name="ModuleMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[("pdf", "PDF")], default="pdf", max_length=32
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=settings.PRIVATE_MEDIA_ROOT
                        ),
                        upload_to="education/materials/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="education_platform.module",
                    ),
                ),
            ],
            options={
                "ordering": ["module_id", "order", "id"],
            },
        ),
    ]
