# Generated by Django 5.2.4 on 2026-05-21 09:07

from django.db import migrations, models


def migrate_legacy_departments(apps, schema_editor):
    Department = apps.get_model("education_platform", "Department")
    TraineeProfile = apps.get_model("education_platform", "TraineeProfile")

    for profile in TraineeProfile.objects.all():
        department_code = str((profile.stats or {}).get("department", "")).strip()
        if not department_code:
            continue
        department = Department.objects.filter(code=department_code, is_active=True).first()
        if department:
            profile.departments.add(department)


class Migration(migrations.Migration):

    dependencies = [
        ("education_platform", "0006_module_private_video_modulematerial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprofile",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="trainees", to="education_platform.department"
            ),
        ),
        migrations.RunPython(migrate_legacy_departments, migrations.RunPython.noop),
    ]
