name: monolith

services:
  monolith:
    build: .
    container_name: pravburo_monolith
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: pravburo_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
