name: documents_service

services:
  backend:
    build: ./backend
    container_name: documents_backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8005:8005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
