# Generated by Django 5.2.4 on 2026-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_withdrawals", "0002_alter_clientwithdrawalrecord_transferred_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientwithdrawalrecord",
            name="withdrawal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Сумма снятия",
            ),
        ),
        migrations.AlterField(
            model_name="clientwithdrawalrecord",
            name="withdrawal_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата снятия"),
        ),
    ]
