# Generated by Django 5.2.4 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="isBlocked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="isBlocked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
