# Generated by Django 5.2.4 on 2025-09-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_stagetemplate_client_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='need_stage_popup',
            field=models.BooleanField(default=False, help_text='Нужно ли показать попап при входе'),
        ),
        migrations.AddField(
            model_name='client',
            name='stage_popup_shown',
            field=models.BooleanField(default=False, help_text='Попап показан и закрыт пользователем'),
        ),
    ]
