# Generated by Django 5.2.4 on 2025-07-29 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_stagetemplate_clientstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.stagetemplate'),
        ),
        migrations.DeleteModel(
            name='ClientStage',
        ),
    ]
