# Generated by Django 5.2.4 on 2025-09-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_dashboardvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardvisit',
            options={},
        ),
        migrations.RemoveField(
            model_name='dashboardvisit',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='dashboardvisit',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='dashboardvisit',
            name='visits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dashboardvisit',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
