# Generated by Django 5.2.4 on 2025-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_dashboardvisit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardvisit',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='dashboardvisit',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardvisit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
