# Generated by Django 5.2.4 on 2025-09-01 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_stage_delete_clientstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
