# Generated by Django 5.2.4 on 2025-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_dashboardvisit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='ID клиента в старой системе', null=True, unique=True),
        ),
    ]
