# Generated by Django 5.2.4 on 2025-11-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='bitrix_stage_id',
            field=models.CharField(blank=True, help_text="ID стадии сделки в Битрикс24 (например, 'C1:NEW' или 'C2:WON')", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stagetemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Описание стадии', null=True),
        ),
    ]
