# Generated by Django 5.2.4 on 2025-09-11 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_application_referralclick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bitrix_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('bitrix_id', None), _negated=True), fields=('bitrix_id',), name='unique_bitrix_id_not_null'),
        ),
    ]
