# Generated by Django 5.2.4 on 2025-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_bitrix_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagetemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
