name: urlshorter_service

services:
  backend:
    build: ./backend
    container_name: urlshorter_backend
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://pravburo:pravburo@shared_postgres:5432/pravburo}
    volumes:
      - ./backend:/app
    ports:
      - "8011:8011"
    networks:
      - default
      - pravburo_shared

  frontend:
    build: ./frontend
    container_name: urlshorter_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8011
      VITE_ADMIN_PANEL_BASE_URL: http://localhost:5176
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5179:5179"
    depends_on:
      - backend

networks:
  pravburo_shared:
    external: true
