# Generated by Django 5.2.4 on 2026-02-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_region_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PmRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='С какой даты действует этот ПМ')),
                ('pm_working', models.DecimalField(decimal_places=2, help_text='ПМ для трудоспособных', max_digits=12)),
                ('pm_pensioner', models.DecimalField(decimal_places=2, help_text='ПМ для пенсионеров', max_digits=12)),
                ('pm_child', models.DecimalField(blank=True, decimal_places=2, help_text='ПМ на ребёнка (опционально, на будущее)', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_rates', to='bitrix.region')),
            ],
            options={
                'verbose_name': 'ПМ по региону',
                'verbose_name_plural': 'ПМ по регионам',
                'ordering': ('region__name', '-effective_from'),
                'constraints': [models.UniqueConstraint(fields=('region', 'effective_from'), name='uniq_pm_rate_region_effective_from')],
            },
        ),
    ]
