"""initial

Revision ID: 90c7026ddffb
Revises: 
Create Date: 2026-07-23 09:27:23.168458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c7026ddffb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('lead_id', sa.String(length=128), nullable=False),
    sa.Column('deal_id', sa.String(length=128), nullable=False),
    sa.Column('contact_id', sa.String(length=128), nullable=False),
    sa.Column('record_file_id', sa.String(length=128), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_webhook_events_call_id'), 'call_webhook_events', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_webhook_events_dedupe_key'), 'call_webhook_events', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_call_webhook_events_status'), 'call_webhook_events', ['status'], unique=False)
    op.create_table('processed_call_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('lead_id', sa.String(length=128), nullable=False),
    sa.Column('deal_id', sa.String(length=128), nullable=False),
    sa.Column('contact_id', sa.String(length=128), nullable=False),
    sa.Column('record_file_id', sa.String(length=128), nullable=False),
    sa.Column('audio_file_path', sa.String(length=512), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_call_archive_call_id'), 'processed_call_archive', ['call_id'], unique=False)
    op.create_index(op.f('ix_processed_call_archive_contact_id'), 'processed_call_archive', ['contact_id'], unique=False)
    op.create_index(op.f('ix_processed_call_archive_created_at'), 'processed_call_archive', ['created_at'], unique=False)
    op.create_index(op.f('ix_processed_call_archive_deal_id'), 'processed_call_archive', ['deal_id'], unique=False)
    op.create_index(op.f('ix_processed_call_archive_lead_id'), 'processed_call_archive', ['lead_id'], unique=False)
    op.create_index(op.f('ix_processed_call_archive_source_event_id'), 'processed_call_archive', ['source_event_id'], unique=False)
    op.create_table('call_processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['call_webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_processing_logs_event_id'), 'call_processing_logs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_processing_logs_event_id'), table_name='call_processing_logs')
    op.drop_table('call_processing_logs')
    op.drop_index(op.f('ix_processed_call_archive_source_event_id'), table_name='processed_call_archive')
    op.drop_index(op.f('ix_processed_call_archive_lead_id'), table_name='processed_call_archive')
    op.drop_index(op.f('ix_processed_call_archive_deal_id'), table_name='processed_call_archive')
    op.drop_index(op.f('ix_processed_call_archive_created_at'), table_name='processed_call_archive')
    op.drop_index(op.f('ix_processed_call_archive_contact_id'), table_name='processed_call_archive')
    op.drop_index(op.f('ix_processed_call_archive_call_id'), table_name='processed_call_archive')
    op.drop_table('processed_call_archive')
    op.drop_index(op.f('ix_call_webhook_events_status'), table_name='call_webhook_events')
    op.drop_index(op.f('ix_call_webhook_events_dedupe_key'), table_name='call_webhook_events')
    op.drop_index(op.f('ix_call_webhook_events_call_id'), table_name='call_webhook_events')
    op.drop_table('call_webhook_events')
    # ### end Alembic commands ###
