version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: system-redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py migrate communications --database=logs &&
             python manage.py migrate communications --database=archive &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Django отправляет задачи в Redis по этому URL.
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: system-worker
    # worker слушает очередь "celery" и выполняет задачи из tasks.py
    command: celery -A system worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
